import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class CountryServiceService {
  constructor() {}
  region = {
    India: [
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chhattisgarh',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jammu and Kashmir',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttarakhand',
      'Uttar Pradesh',
      'West Bengal',
      'Andaman and Nicobar Islands',
      'Chandigarh',
      'Dadra and Nagar Haveli',
      'Daman and Diu',
      'Delhi',
      'Lakshadweep',
      'Puducherry',
    ],
    'Saudi Arabia': [
      'Abhā',
      'Abqaiq',
      'Al-Baḥah',
      'Al-Dammām',
      'Al-Hufūf',
      'Al-Jawf',
      'Al-Kharj',
      'AlKhubar',
      'AlQaṭīf',
      'AlṬaif',
      'Arar',
      'Buraydah',
      'Dhahran',
      'Ḥāil',
      'Jiddah',
      'Jīzān',
      'KhamīsMushayt',
      'King Khalīd Military City',
      'Mecca',
      'Medina',
      'Najrān',
      'RasTanura',
      'Riyadh',
      'Sakākā',
      'Tabūk',
      'Yanbu',
    ],
    Malaysia: [
      'Johor',
      'Kedah',
      'Kelantan',
      'Melaka',
      'Negeri Sembilan',
      'Pahang',
      'Perak',
      'Perlis',
      'Pulau Pinang',
      'Sabah',
      'Sarawak',
      'Selangor',
      'Terengganu',
    ],
    Singapore: [
      'Central Region',
      'North Region',
      'Northeast Region',
      'East Region',
      'West Region',
    ],
    Morocco: [
      'Tanger-Tetouan-Al Hoceima',
      'Oriental',
      'Fès-Meknès',
      'Rabat-Salé-Kénitra',
      'Béni Mellal-Khénifra',
      'Casablanca-Settat',
      'Marrakech-Safi',
      'Drâa-Tafilalet',
      'Souss-Massa',
      'Guelmim-Oued Noun',
      'Laâyoune-Sakia El Hamra',
      'Dakhla-Oued Ed-Dahab',
      'Tanger-Assilah',
    ],
    Egypt: [
      'Alexandria',
      'Aswan',
      'Asyut',
      'Beheira',
      'Beni Suef',
      'Cairo',
      'Dakahlia',
      'Damietta',
      'Faiyum',
      'Gharbia',
      'Giza',
      'Ismailia',
      'Kafr El Sheikh',
      'Luxor',
      'Matrouh',
      'Minya',
      'Monufia',
      'New Valley',
      'North Sinai',
      'Port Said',
      'Qalyubia',
      'Qena',
      'Red Sea',
      'Sharqia',
      'Sohag',
      'South Sinai',
      'Suez',
    ],
    Kenya: [
      'Baringo',
      'Bomet',
      'Bungoma',
      'Busia',
      'Elgeyo-Marakwet',
      'Embu',
      'Garissa',
      'Homa Bay',
      'Isiolo',
      'Kajiado',
      'Kakamega',
      'Kericho',
      'Kiambu',
      'Kilifi',
      'Kirinyaga',
      'Kisii',
      'Kisumu',
      'Kitui',
      'Kwale',
      'Laikipia',
      'Lamu',
      'Machakos',
      'Makueni',
      'Mandera',
      'Marsabit',
      'Meru',
      'Migori',
      'Mombasa',
      "Murang'a",
      'Nairobi',
      'Nakuru',
      'Nandi',
      'Narok',
      'Nyamira',
      'Nyandarua',
      'Nyeri',
      'Samburu',
      'Siaya',
      'Taita-Taveta',
      'Tana River',
      'Tharaka-Nithi',
      'Trans Nzoia',
      'Turkana',
      'Uasin Gishu',
      'Vihiga',
      'Wajir',
      'West Pokot',
    ],
  };

  //  states ={"Andhra Pradesh":[" Achampet ",
  //  " Adilabad ", "Adoni ", "Alampur ", "Allagadda ", "Alur "," Amalapuram "," Amangallu "," Anakapalle "," Anantapur "," Andole "," Araku "," Armoor "," Asifabad "," Aswaraopet "," Atmakur "," B. Kothakota "," Badvel "," Banaganapalle "," Bandar "," Bangarupalem "," Banswada "," Bapatla "," Bellampalli "," Bhadrachalam "," Bhainsa "," Bheemunipatnam "," Bhimadole "," Bhimavaram "," Bhongir "," Bhooragamphad "," Boath "," Bobbili "," Bodhan "," Chandoor "," Chavitidibbalu "," Chejerla "," Chepurupalli "," Cherial "," Chevella "," Chinnor "," Chintalapudi "," Chintapalle "," Chirala "," Chittoor "," Chodavaram "," Cuddapah "," Cumbum "," Darsi "," Devarakonda "," Dharmavaram "," Dichpalli "," Divi "," Donakonda "," Dronachalam "," East Godavari "," Eluru "," Eturnagaram "," Gadwal "," Gajapathinagaram "," Gajwel "," Garladinne "," Giddalur "," Godavari "," Gooty "," Gudivada "," Gudur "," Guntur "," Hindupur "," Hunsabad "," Huzurabad "," Huzurnagar "," Hyderabad "," Ibrahimpatnam "," Jaggayyapet "," Jagtial "," Jammalamadugu "," Jangaon "," Jangareddygudem "," Jannaram "," Kadiri "," Kaikaluru "," Kakinada "," Kalwakurthy "," Kalyandurg "," Kamalapuram "," Kamareddy "," Kambadur "," Kanaganapalle "," Kandukuru "," Kanigiri "," Karimnagar "," Kavali "," Khammam "," Khanapur (AP) "," Kodangal "," Koduru "," Koilkuntla "," Kollapur "," Kothagudem "," Kovvur "," Krishna "," Krosuru "," Kuppam "," Kurnool "," Lakkireddipalli "," Madakasira "," Madanapalli "," Madhira "," Madnur "," Mahabubabad "," Mahabubnagar "," Mahadevapur "," Makthal "," Mancherial "," Mandapeta "," Mangalagiri "," Manthani "," Markapur "," Marturu "," Medachal "," Medak "," Medarmetla "," Metpalli "," Mriyalguda "," Mulug "," Mylavaram "," Nagarkurnool "," Nalgonda "," Nallacheruvu "," Nampalle "," Nandigama "," Nandikotkur "," Nandyal "," Narasampet "," Narasaraopet "," Narayanakhed "," Narayanpet "," Narsapur "," Narsipatnam "," Nazvidu "," Nelloe "," Nellore "," Nidamanur "," Nirmal "," Nizamabad "," Nuguru "," Ongole "," Outsarangapalle "," Paderu "," Pakala "," Palakonda "," Paland "," Palmaneru "," Pamuru "," Pargi "," Parkal "," Parvathipuram "," Pathapatnam "," Pattikonda "," Peapalle "," Peddapalli "," Peddapuram "," Penukonda "," Piduguralla "," Piler "," Pithapuram "," Podili "," Polavaram "," Prakasam "," Proddatur "," Pulivendla "," Punganur "," Putturu "," Rajahmundri "," Rajampeta "," Ramachandrapuram "," Ramannapet "," Rampachodavaram "," Rangareddy "," Rapur "," Rayachoti "," Rayadurg "," Razole "," Repalle "," Saluru "," Sangareddy "," Sathupalli "," Sattenapalle "," Satyavedu "," Shadnagar "," Siddavattam "," Siddipet "," Sileru "," Sircilla "," Sirpur Kagaznagar "," Sodam "," Sompeta "," Srikakulam "," Srikalahasthi "," Srisailam "," Srungavarapukota "," Sudhimalla "," Sullarpet "," Tadepalligudem "," Tadipatri "," Tanduru "," Tanuku "," Tekkali "," Tenali "," Thungaturthy "," Tirivuru "," Tirupathi "," Tuni "," Udaygiri "," Ulvapadu "," Uravakonda "," Utnor "," V.R. Puram "," Vaimpalli "," Vayalpad "," Venkatgiri "," Venkatgirikota "," Vijayawada "," Vikrabad "," Vinjamuru "," Vinukonda "," Visakhapatnam "," Vizayanagaram "," Vizianagaram "," Vuyyuru "," Wanaparthy "," Warangal "," Wardhannapet "," Yelamanchili "," Yelavaram "," Yeleswaram "," Yellandu "," Yellanuru "," Yellareddy "," Yerragondapalem "," Zahirabad "]}
  // }

  states = {
    // tamil nadu
    'Andaman and Nicobar Islands': ['Port Blair'],
    'Andhra Pradesh': [
      'Adoni',
      'Amalapuram',
      'Anakapalle',
      'Anantapur',
      'Bapatla',
      'Bheemunipatnam',
      'Bhimavaram',
      'Bobbili',
      'Chilakaluripet',
      'Chirala',
      'Chittoor',
      'Dharmavaram',
      'Eluru',
      'Gooty',
      'Gudivada',
      'Gudur',
      'Guntakal',
      'Guntur',
      'Hindupur',
      'Jaggaiahpet',
      'Jammalamadugu',
      'Kadapa',
      'Kadiri',
      'Kakinada',
      'Kandukur',
      'Kavali',
      'Kovvur',
      'Kurnool',
      'Macherla',
      'Machilipatnam',
      'Madanapalle',
      'Mandapeta',
      'Markapur',
      'Nagari',
      'Naidupet',
      'Nandyal',
      'Narasapuram',
      'Narasaraopet',
      'Narsipatnam',
      'Nellore',
      'Nidadavole',
      'Nuzvid',
      'Ongole',
      'Palacole',
      'Palasa Kasibugga',
      'Parvathipuram',
      'Pedana',
      'Peddapuram',
      'Pithapuram',
      'Ponnur',
      'Proddatur',
      'Punganur',
      'Puttur',
      'Rajahmundry',
      'Rajam',
      'Rajampet',
      'Ramachandrapuram',
      'Rayachoti',
      'Rayadurg',
      'Renigunta',
      'Repalle',
      'Salur',
      'Samalkot',
      'Sattenapalle',
      'Srikakulam',
      'Srikalahasti',
      'Srisailam Project (Right Flank Colony) Township',
      'Sullurpeta',
      'Tadepalligudem',
      'Tadpatri',
      'Tanuku',
      'Tenali',
      'Tirupati',
      'Tiruvuru',
      'Tuni',
      'Uravakonda',
      'Venkatagiri',
      'Vijayawada',
      'Vinukonda',
      'Visakhapatnam',
      'Vizianagaram',
      'Yemmiganur',
      'Yerraguntla',
    ],
    'Arunachal Pradesh': ['Naharlagun', 'Pasighat'],
    Assam: [
      'Barpeta',
      'Bongaigaon City',
      'Dhubri',
      'Dibrugarh',
      'Diphu',
      'Goalpara',
      'Guwahati',
      'Jorhat',
      'Karimganj',
      'Lanka',
      'Lumding',
      'Mangaldoi',
      'Mankachar',
      'Margherita',
      'Mariani',
      'Marigaon',
      'Nagaon',
      'Nalbari',
      'North Lakhimpur',
      'Rangia',
      'Sibsagar',
      'Silapathar',
      'Silchar',
      'Tezpur',
      'Tinsukia',
    ],
    Bihar: [
      'Araria',
      'Arrah',
      'Arwal',
      'Asarganj',
      'Aurangabad',
      'Bagaha',
      'Barh',
      'Begusarai',
      'Bettiah',
      'Bhabua',
      'Bhagalpur',
      'Buxar',
      'Chhapra',
      'Darbhanga',
      'Dehri-on-Sone',
      'Dumraon',
      'Forbesganj',
      'Gaya',
      'Gopalganj',
      'Hajipur',
      'Jamalpur',
      'Jamui',
      'Jehanabad',
      'Katihar',
      'Kishanganj',
      'Lakhisarai',
      'Lalganj',
      'Madhepura',
      'Madhubani',
      'Maharajganj',
      'Mahnar Bazar',
      'Makhdumpur',
      'Maner',
      'Manihari',
      'Marhaura',
      'Masaurhi',
      'Mirganj',
      'Mokameh',
      'Motihari',
      'Motipur',
      'Munger',
      'Murliganj',
      'Muzaffarpur',
      'Narkatiaganj',
      'Naugachhia',
      'Nawada',
      'Nokha',
      'Patna',
      'Piro',
      'Purnia',
      'Rafiganj',
      'Rajgir',
      'Ramnagar',
      'Raxaul Bazar',
      'Revelganj',
      'Rosera',
      'Saharsa',
      'Samastipur',
      'Sasaram',
      'Sheikhpura',
      'Sheohar',
      'Sherghati',
      'Silao',
      'Sitamarhi',
      'Siwan',
      'Sonepur',
      'Sugauli',
      'Sultanganj',
      'Supaul',
      'Warisaliganj',
    ],
    Chandigarh: ['Chandigarh'],
    Chhattisgarh: [
      'Ambikapur',
      'Bhatapara',
      'Bhilai Nagar',
      'Bilaspur',
      'Chirmiri',
      'Dalli-Rajhara',
      'Dhamtari',
      'Durg',
      'Jagdalpur',
      'Korba',
      'Mahasamund',
      'Manendragarh',
      'Mungeli',
      'Naila Janjgir',
      'Raigarh',
      'Raipur',
      'Rajnandgaon',
      'Sakti',
      'Tilda Newra',
    ],
    'Dadra and Nagar Haveli': ['Silvassa'],
    Delhi: ['Delhi', 'New Delhi'],
    Goa: ['Mapusa', 'Margao', 'Marmagao', 'Panaji'],
    Gujarat: [
      'Adalaj',
      'Ahmedabad',
      'Amreli',
      'Anand',
      'Anjar',
      'Ankleshwar',
      'Bharuch',
      'Bhavnagar',
      'Bhuj',
      'Chhapra',
      'Deesa',
      'Dhoraji',
      'Godhra',
      'Jamnagar',
      'Kadi',
      'Kapadvanj',
      'Keshod',
      'Khambhat',
      'Lathi',
      'Limbdi',
      'Lunawada',
      'Mahesana',
      'Mahuva',
      'Manavadar',
      'Mandvi',
      'Mangrol',
      'Mansa',
      'Mahemdabad',
      'Modasa',
      'Morvi',
      'Nadiad',
      'Navsari',
      'Padra',
      'Palanpur',
      'Palitana',
      'Pardi',
      'Patan',
      'Petlad',
      'Porbandar',
      'Radhanpur',
      'Rajkot',
      'Rajpipla',
      'Rajula',
      'Ranavav',
      'Rapar',
      'Salaya',
      'Sanand',
      'Savarkundla',
      'Sidhpur',
      'Sihor',
      'Songadh',
      'Surat',
      'Talaja',
      'Thangadh',
      'Tharad',
      'Umbergaon',
      'Umreth',
      'Una',
      'Unjha',
      'Upleta',
      'Vadnagar',
      'Vadodara',
      'Valsad',
      'Vapi',
      'Vapi',
      'Veraval',
      'Vijapur',
      'Viramgam',
      'Visnagar',
      'Vyara',
      'Wadhwan',
      'Wankaner',
    ],
    Haryana: [
      'Bahadurgarh',
      'Bhiwani',
      'Charkhi Dadri',
      'Faridabad',
      'Fatehabad',
      'Gohana',
      'Gurgaon',
      'Hansi',
      'Hisar',
      'Jind',
      'Kaithal',
      'Karnal',
      'Ladwa',
      'Mahendragarh',
      'Mandi Dabwali',
      'Narnaul',
      'Narwana',
      'Palwal',
      'Panchkula',
      'Panipat',
      'Pehowa',
      'Pinjore',
      'Rania',
      'Ratia',
      'Rewari',
      'Rohtak',
      'Safidon',
      'Samalkha',
      'Sarsod',
      'Shahbad',
      'Sirsa',
      'Sohna',
      'Sonipat',
      'Taraori',
      'Thanesar',
      'Tohana',
      'Yamunanagar',
    ],
    'Himachal Pradesh': [
      'Mandi',
      'Nahan',
      'Palampur',
      'Shimla',
      'Solan',
      'Sundarnagar',
    ],
    'Jammu and Kashmir': [
      'Anantnag',
      'Badgam',
      'Bandipore',
      'Baramula',
      'Doda',
      'Ganderbal',
      'Jammu',
      'Kargil',
      'Kathua',
      'Kishtwar',
      'Kulgam',
      'Kupwara',
      'Leh',
      'Pulwama',
      'Punch',
      'Rajouri',
      'Ramban',
      'Reasi',
      'Samba',
      'Shopian',
      'Srinagar',
      'Udhampur',
    ],
    Jharkhand: [
      'Adityapur',
      'Bokaro Steel City',
      'Chaibasa',
      'Chatra',
      'Chirkunda',
      'Medininagar (Daltonganj)',
      'Deoghar',
      'Dhanbad',
      'Dumka',
      'Giridih',
      'Gumia',
      'Hazaribag',
      'Jamshedpur',
      'Jhumri Tilaiya',
      'Lohardaga',
      'Madhupur',
      'Mihijam',
      'Musabani',
      'Pakaur',
      'Patratu',
      'Phusro',
      'Ramgarh',
      'Ranchi',
      'Sahibganj',
      'Saunda',
      'Simdega',
      'Tenu dam-cum-Kathhara',
    ],
    Karnataka: [
      'Adyar',
      'Afzalpur',
      'Arsikere',
      'Athni',
      'Bengaluru',
      'Belagavi',
      'Ballari',
      'Chikkamagaluru',
      'Davanagere',
      'Gokak',
      'Hubli-Dharwad',
      'Karwar',
      'Kolar',
      'Lakshmeshwar',
      'Lingsugur',
      'Maddur',
      'Madhugiri',
      'Madikeri',
      'Magadi',
      'Mahalingapura',
      'Malavalli',
      'Malur',
      'Mandya',
      'Mangaluru',
      'Manvi',
      'Mudalagi',
      'Mudabidri',
      'Muddebihal',
      'Mudhol',
      'Mulbagal',
      'Mundargi',
      'Nanjangud',
      'Nargund',
      'Navalgund',
      'Nelamangala',
      'Pavagada',
      'Piriyapatna',
      'Puttur',
      'Rabkavi Banhatti',
      'Raayachuru',
      'Ranebennuru',
      'Ramanagaram',
      'Ramdurg',
      'Ranibennur',
      'Robertson Pet',
      'Ron',
      'Sadalagi',
      'Sagara',
      'Sakaleshapura',
      'Sindagi',
      'Sanduru',
      'Sankeshwara',
      'Saundatti-Yellamma',
      'Savanur',
      'Sedam',
      'Shahabad',
      'Shahpur',
      'Shiggaon',
      'Shikaripur',
      'Shivamogga',
      'Surapura',
      'Shrirangapattana',
      'Sidlaghatta',
      'Sindhagi',
      'Sindhnur',
      'Sira',
      'Sirsi',
      'Siruguppa',
      'Srinivaspur',
      'Tarikere',
      'Tekkalakote',
      'Terdal',
      'Talikota',
      'Tiptur',
      'Tumkur',
      'Udupi',
      'Vijayapura',
      'Wadi',
      'Yadgir',
    ],
    Karnatka: ['Mysore'],
    Kerala: [
      'Adoor',
      'Alappuzha',
      'Attingal',
      'Chalakudy',
      'Changanassery',
      'Cherthala',
      'Chittur-Thathamangalam',
      'Guruvayoor',
      'Kanhangad',
      'Kannur',
      'Kasaragod',
      'Kayamkulam',
      'Kochi',
      'Kodungallur',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Kunnamkulam',
      'Malappuram',
      'Mattannur',
      'Mavelikkara',
      'Mavoor',
      'Muvattupuzha',
      'Nedumangad',
      'Neyyattinkara',
      'Nilambur',
      'Ottappalam',
      'Palai',
      'Palakkad',
      'Panamattom',
      'Panniyannur',
      'Pappinisseri',
      'Paravoor',
      'Pathanamthitta',
      'Peringathur',
      'Perinthalmanna',
      'Perumbavoor',
      'Ponnani',
      'Punalur',
      'Puthuppally',
      'Koyilandy',
      'Shoranur',
      'Taliparamba',
      'Thiruvalla',
      'Thiruvananthapuram',
      'Thodupuzha',
      'Thrissur',
      'Tirur',
      'Vaikom',
      'Varkala',
      'Vatakara',
    ],
    'Madhya Pradesh': [
      'Alirajpur',
      'Anuppur',
      'Ashok Nagar',
      'Balaghat',
      'Barwani',
      'Betul',
      'Bhind',
      'Bhopal',
      'Burhanpur',
      'Chhatarpur',
      'Chhindwara',
      'Damoh',
      'Datia',
      'Dewas',
      'Dhar',
      'Dindori',
      'East Nimar',
      'Guna',
      'Gwalior',
      'Harda',
      'Hoshangabad',
      'Indore',
      'Jabalpur',
      'Jhabua',
      'Katni',
      'Khandwa',
      'Khargone',
      'Mandla',
      'Mandsaur',
      'Morena',
      'Narsinghpur',
      'Neemuch',
      'Panna',
      'Raisen',
      'Rajgarh',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Satna',
      'Sehore',
      'Seoni',
      'Shahdol',
      'Shajapur',
      'Sheopur',
      'Shivpuri',
      'Sidhi',
      'Singrauli',
      'Tikamgarh',
      'Ujjain',
      'Umaria',
      'Vidisha',
      'West Nimar',
    ],
    Maharashtra: [
      '[[]]',
      'Ahmednagar',
      'Akola',
      'Akot',
      'Amalner',
      'Ambejogai',
      'Amravati',
      'Anjangaon',
      'Arvi',
      'Aurangabad',
      'Bhiwandi',
      'Dhule',
      'Kalyan-Dombivali',
      'Ichalkaranji',
      'Kalyan-Dombivali',
      'Karjat',
      'Latur',
      'Loha',
      'Lonar',
      'Lonavla',
      'Mahad',
      'Malegaon',
      'Malkapur',
      'Mangalvedhe',
      'Mangrulpir',
      'Manjlegaon',
      'Manmad',
      'Manwath',
      'Mehkar',
      'Mhaswad',
      'Mira-Bhayandar',
      'Morshi',
      'Mukhed',
      'Mul',
      'Greater Mumbai',
      'Murtijapur',
      'Nagpur',
      'Nanded-Waghala',
      'Nandgaon',
      'Nandura',
      'Nandurbar',
      'Narkhed',
      'Nashik',
      'Navi Mumbai',
      'Nawapur',
      'Nilanga',
      'Osmanabad',
      'Ozar',
      'Pachora',
      'Paithan',
      'Palghar',
      'Pandharkaoda',
      'Pandharpur',
      'Panvel',
      'Parbhani',
      'Parli',
      'Partur',
      'Pathardi',
      'Pathri',
      'Patur',
      'Pauni',
      'Pen',
      'Phaltan',
      'Pulgaon',
      'Pune',
      'Purna',
      'Pusad',
      'Rahuri',
      'Rajura',
      'Ramtek',
      'Ratnagiri',
      'Raver',
      'Risod',
      'Sailu',
      'Sangamner',
      'Sangli',
      'Sangole',
      'Sasvad',
      'Satana',
      'Satara',
      'Savner',
      'Sawantwadi',
      'Shahade',
      'Shegaon',
      'Shendurjana',
      'Shirdi',
      'Shirpur-Warwade',
      'Shirur',
      'Shrigonda',
      'Shrirampur',
      'Sillod',
      'Sinnar',
      'Solapur',
      'Soyagaon',
      'Talegaon Dabhade',
      'Talode',
      'Tasgaon',
      'Thane',
      'Tirora',
      'Tuljapur',
      'Tumsar',
      'Uchgaon',
      'Udgir',
      'Umarga',
      'Umarkhed',
      'Umred',
      'Uran',
      'Uran Islampur',
      'Vadgaon Kasba',
      'Vaijapur',
      'Vasai-Virar',
      'Vita',
      'Wadgaon Road',
      'Wai',
      'Wani',
      'Wardha',
      'Warora',
      'Warud',
      'Washim',
      'Yavatmal',
      'Yawal',
      'Yevla',
    ],
    Manipur: ['Imphal', 'Lilong', 'Mayang Imphal', 'Thoubal'],
    Meghalaya: ['Nongstoin', 'Shillong', 'Tura'],
    Mizoram: ['Aizawl', 'Lunglei', 'Saiha'],
    Nagaland: [
      'Dimapur',
      'Kohima',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto',
    ],
    Odisha: [
      'Balangir',
      'Baleshwar Town',
      'Barbil',
      'Bargarh',
      'Baripada Town',
      'Bhadrak',
      'Bhawanipatna',
      'Bhubaneswar',
      'Brahmapur',
      'Byasanagar',
      'Cuttack',
      'Dhenkanal',
      'Jatani',
      'Jharsuguda',
      'Kendrapara',
      'Kendujhar',
      'Malkangiri',
      'Nabarangapur',
      'Paradip',
      'Parlakhemundi',
      'Pattamundai',
      'Phulabani',
      'Puri',
      'Rairangpur',
      'Rajagangapur',
      'Raurkela',
      'Rayagada',
      'Sambalpur',
      'Soro',
      'Sunabeda',
      'Sundargarh',
      'Talcher',
      'Tarbha',
      'Titlagarh',
    ],
    Puducherry: ['Karaikal', 'Mahe', 'Pondicherry', 'Yanam'],
    Punjab: [
      'Amritsar',
      'Barnala',
      'Batala',
      'Bathinda',
      'Dhuri',
      'Faridkot',
      'Fazilka',
      'Firozpur',
      'Firozpur Cantt.',
      'Gobindgarh',
      'Gurdaspur',
      'Hoshiarpur',
      'Jagraon',
      'Jalandhar Cantt.',
      'Jalandhar',
      'Kapurthala',
      'Khanna',
      'Kharar',
      'Kot Kapura',
      'Longowal',
      'Ludhiana',
      'Malerkotla',
      'Malout',
      'Mansa',
      'Moga',
      'Mohali',
      'Morinda, India',
      'Mukerian',
      'Muktsar',
      'Nabha',
      'Nakodar',
      'Nangal',
      'Nawanshahr',
      'Pathankot',
      'Patiala',
      'Pattran',
      'Patti',
      'Phagwara',
      'Phillaur',
      'Qadian',
      'Raikot',
      'Rajpura',
      'Rampura Phul',
      'Rupnagar',
      'Samana',
      'Sangrur',
      'Sirhind Fatehgarh Sahib',
      'Sujanpur',
      'Sunam',
      'Talwara',
      'Tarn Taran',
      'Urmar Tanda',
      'Zira',
      'Zirakpur',
    ],
    Rajasthan: [
      'Ajmer',
      'Alwar',
      'Bikaner',
      'Bharatpur',
      'Bhilwara',
      'Jaipur',
      'Jodhpur',
      'Lachhmangarh',
      'Ladnu',
      'Lakheri',
      'Lalsot',
      'Losal',
      'Makrana',
      'Malpura',
      'Mandalgarh',
      'Mandawa',
      'Mangrol',
      'Merta City',
      'Mount Abu',
      'Nadbai',
      'Nagar',
      'Nagaur',
      'Nasirabad',
      'Nathdwara',
      'Neem-Ka-Thana',
      'Nimbahera',
      'Nohar',
      'Nokha',
      'Pali',
      'Phalodi',
      'Phulera',
      'Pilani',
      'Pilibanga',
      'Pindwara',
      'Pipar City',
      'Prantij',
      'Pratapgarh',
      'Raisinghnagar',
      'Rajakhera',
      'Rajaldesar',
      'Rajgarh (Alwar)',
      'Rajgarh (Churu)',
      'Rajsamand',
      'Ramganj Mandi',
      'Ramngarh',
      'Ratangarh',
      'Rawatbhata',
      'Rawatsar',
      'Reengus',
      'Sadri',
      'Sadulshahar',
      'Sadulpur',
      'Sagwara',
      'Sambhar',
      'Sanchore',
      'Sangaria',
      'Sardarshahar',
      'Sawai Madhopur',
      'Shahpura',
      'Shahpura',
      'Sheoganj',
      'Sikar',
      'Sirohi',
      'Sojat',
      'Sri Madhopur',
      'Sujangarh',
      'Sumerpur',
      'Suratgarh',
      'Taranagar',
      'Todabhim',
      'Todaraisingh',
      'Tonk',
      'Udaipur',
      'Udaipurwati',
      'Vijainagar, Ajmer',
    ],
    'Tamil Nadu': [
      'Arakkonam',
      'Aruppukkottai',
      'Chennai',
      'Coimbatore',
      'Erode',
      'Gobichettipalayam',
      'Kancheepuram',
      'Karur',
      'Lalgudi',
      'Madurai',
      'Manachanallur',
      'Nagapattinam',
      'Nagercoil',
      'Namagiripettai',
      'Namakkal',
      'Nandivaram-Guduvancheri',
      'Nanjikottai',
      'Natham',
      'Nellikuppam',
      'Neyveli (TS)',
      "O' Valley",
      'Oddanchatram',
      'P.N.Patti',
      'Pacode',
      'Padmanabhapuram',
      'Palani',
      'Palladam',
      'Pallapatti',
      'Pallikonda',
      'Panagudi',
      'Panruti',
      'Paramakudi',
      'Parangipettai',
      'Pattukkottai',
      'Perambalur',
      'Peravurani',
      'Periyakulam',
      'Periyasemur',
      'Pernampattu',
      'Pollachi',
      'Polur',
      'Ponneri',
      'Pudukkottai',
      'Pudupattinam',
      'Puliyankudi',
      'Punjaipugalur',
      'Ranipet',
      'Rajapalayam',
      'Ramanathapuram',
      'Rameshwaram',
      'Rasipuram',
      'Salem',
      'Sankarankoil',
      'Sankari',
      'Sathyamangalam',
      'Sattur',
      'Shenkottai',
      'Sholavandan',
      'Sholingur',
      'Sirkali',
      'Sivaganga',
      'Sivagiri',
      'Sivakasi',
      'Srivilliputhur',
      'Surandai',
      'Suriyampalayam',
      'Tenkasi',
      'Thammampatti',
      'Thanjavur',
      'Tharamangalam',
      'Tharangambadi',
      'Theni Allinagaram',
      'Thirumangalam',
      'Thirupuvanam',
      'Thiruthuraipoondi',
      'Thiruvallur',
      'Thiruvarur',
      'Thuraiyur',
      'Tindivanam',
      'Tiruchendur',
      'Tiruchengode',
      'Tiruchirappalli',
      'Tirukalukundram',
      'Tirukkoyilur',
      'Tirunelveli',
      'Tirupathur',
      'Tirupathur',
      'Tiruppur',
      'Tiruttani',
      'Tiruvannamalai',
      'Tiruvethipuram',
      'Tittakudi',
      'Udhagamandalam',
      'Udumalaipettai',
      'Unnamalaikadai',
      'Usilampatti',
      'Uthamapalayam',
      'Uthiramerur',
      'Vadakkuvalliyur',
      'Vadalur',
      'Vadipatti',
      'Valparai',
      'Vandavasi',
      'Vaniyambadi',
      'Vedaranyam',
      'Vellakoil',
      'Vellore',
      'Vikramasingapuram',
      'Viluppuram',
      'Virudhachalam',
      'Virudhunagar',
      'Viswanatham',
    ],
    Telangana: [
      'Adilabad',
      'Bellampalle',
      'Bhadrachalam',
      'Bhainsa',
      'Bhongir',
      'Bodhan',
      'Farooqnagar',
      'Gadwal',
      'Hyderabad',
      'Jagtial',
      'Jangaon',
      'Kagaznagar',
      'Kamareddy',
      'Karimnagar',
      'Khammam',
      'Koratla',
      'Kothagudem',
      'Kyathampalle',
      'Mahbubnagar',
      'Mancherial',
      'Mandamarri',
      'Manuguru',
      'Medak',
      'Miryalaguda',
      'Nagarkurnool',
      'Narayanpet',
      'Nirmal',
      'Nizamabad',
      'Palwancha',
      'Ramagundam',
      'Sadasivpet',
      'Sangareddy',
      'Siddipet',
      'Sircilla',
      'Suryapet',
      'Tandur',
      'Vikarabad',
      'Wanaparthy',
      'Warangal',
      'Yellandu',
    ],
    Tripura: [
      'Agartala',
      'Belonia',
      'Dharmanagar',
      'Kailasahar',
      'Khowai',
      'Pratapgarh',
      'Udaipur',
    ],
    'Uttar Pradesh': [
      'Achhnera',
      'Agra',
      'Aligarh',
      'Allahabad',
      'Amroha',
      'Azamgarh',
      'Bahraich',
      'Chandausi',
      'Etawah',
      'Firozabad',
      'Fatehpur Sikri',
      'Hapur',
      'Hardoi ',
      'Jhansi',
      'Kalpi',
      'Kanpur',
      'Khair',
      'Laharpur',
      'Lakhimpur',
      'Lal Gopalganj Nindaura',
      'Lalitpur',
      'Lalganj',
      'Lar',
      'Loni',
      'Lucknow',
      'Mathura',
      'Meerut',
      'Modinagar',
      'Moradabad',
      'Nagina',
      'Najibabad',
      'Nakur',
      'Nanpara',
      'Naraura',
      'Naugawan Sadat',
      'Nautanwa',
      'Nawabganj',
      'Nehtaur',
      'Niwai',
      'Noida',
      'Noorpur',
      'Obra',
      'Orai',
      'Padrauna',
      'Palia Kalan',
      'Parasi',
      'Phulpur',
      'Pihani',
      'Pilibhit',
      'Pilkhuwa',
      'Powayan',
      'Pukhrayan',
      'Puranpur',
      'Purquazi',
      'Purwa',
      'Rae Bareli',
      'Rampur',
      'Rampur Maniharan',
      'Rampur Maniharan',
      'Rasra',
      'Rath',
      'Renukoot',
      'Reoti',
      'Robertsganj',
      'Rudauli',
      'Rudrapur',
      'Sadabad',
      'Safipur',
      'Saharanpur',
      'Sahaspur',
      'Sahaswan',
      'Sahawar',
      'Sahjanwa',
      'Saidpur',
      'Sambhal',
      'Samdhan',
      'Samthar',
      'Sandi',
      'Sandila',
      'Sardhana',
      'Seohara',
      'Shahabad, Hardoi',
      'Shahabad, Rampur',
      'Shahganj',
      'Shahjahanpur',
      'Shamli',
      'Shamsabad, Agra',
      'Shamsabad, Farrukhabad',
      'Sherkot',
      'Shikarpur, Bulandshahr',
      'Shikohabad',
      'Shishgarh',
      'Siana',
      'Sikanderpur',
      'Sikandra Rao',
      'Sikandrabad',
      'Sirsaganj',
      'Sirsi',
      'Sitapur',
      'Soron',
      'Suar',
      'Sultanpur',
      'Sumerpur',
      'Tanda',
      'Thakurdwara',
      'Thana Bhawan',
      'Tilhar',
      'Tirwaganj',
      'Tulsipur',
      'Tundla',
      'Ujhani',
      'Unnao',
      'Utraula',
      'Varanasi',
      'Vrindavan',
      'Warhapur',
      'Zaidpur',
      'Zamania',
    ],
    Uttarakhand: [
      // "Bageshwar",
      // "Dehradun",
      // "Haldwani-cum-Kathgodam",
      // "Hardwar",
      // "Kashipur",
      // "Manglaur",
      // "Mussoorie",
      // "Nagla",
      // "Nainital",
      // "Pauri",
      // "Pithoragarh",
      // "Ramnagar",
      // "Rishikesh",
      // "Roorkee",
      // "Rudrapur",
      // "Sitarganj",
      // "Srinagar",
      // "Tehri",
      'Almora',
      'Bageshwar',
      'Chamoli',
      'Champawat',
      'Dehra Dun',
      'Haridwar',
      'Nanital',
      'Pauri Garhwal',
      'Pithoragarh',
      'Rudra Prayag',
      'Tehri Garhwal',
      'Udham Singh Nagar',
      'Uttar Kashi',
    ],
    'West Bengal': [
      'Adra',
      'Alipurduar',
      'Arambagh',
      'Asansol',
      'Baharampur',
      'Balurghat',
      'Bankura',
      'Darjiling',
      'English Bazar',
      'Gangarampur',
      'Habra',
      'Hugli-Chinsurah',
      'Jalpaiguri',
      'Jhargram',
      'Kalimpong',
      'Kharagpur',
      'Kolkata',
      'Mainaguri',
      'Malda',
      'Mathabhanga',
      'Medinipur',
      'Memari',
      'Monoharpur',
      'Murshidabad',
      'Nabadwip',
      'Naihati',
      'Panchla',
      'Pandua',
      'Paschim Punropara',
      'Purulia',
      'Raghunathpur',
      'Raghunathganj',
      'Raiganj',
      'Rampurhat',
      'Ranaghat',
      'Sainthia',
      'Santipur',
      'Siliguri',
      'Sonamukhi',
      'Srirampore',
      'Suri',
      'Taki',
      'Tamluk',
      'Tarakeswar',
    ],

    // malaysian
    Johor: [
      'Johor Bahru',
      'Tebrau',
      'Pasir Gudang',
      'Bukit Indah',
      'Skudai',
      'Kluang',
      'Batu Pahat',
      'Muar',
      'Ulu Tiram',
      'Senai',
      'Segamat',
      'Kulai',
      'Kota Tinggi',
      'Pontian Kechil',
      'Tangkak',
      'Bukit Bakri',
      'Yong Peng',
      'Pekan Nenas',
      'Labis',
      'Mersing',
      'Simpang Renggam',
      'Parit Raja',
      'Kelapa Sawit',
      'Buloh Kasap',
      'Chaah',
    ],
    Kedah: [
      'Sungai Petani',
      'Alor Setar',
      'Kulim',
      'Jitra / Kubang Pasu',
      'Baling',
      'Pendang',
      'Langkawi',
      'Yan',
      'Sik',
      'Kuala Nerang',
      'Pokok Sena',
      'Bandar Baharu',
    ],
    Kelantan: [
      'Kota Bharu',
      'Pangkal Kalong',
      'Tanah Merah',
      'Peringat',
      'Wakaf Baru',
      'Kadok',
      'Pasir Mas',
      'Gua Musang',
      'Kuala Krai',
      'Tumpat',
    ],
    Melaka: [
      'Bandaraya Melaka',
      'Bukit Baru',
      'Ayer Keroh',
      'Klebang',
      'Masjid Tanah',
      'Sungai Udang',
      'Batu Berendam',
      'Alor Gajah',
      'Bukit Rambai',
      'Ayer Molek',
      'Bemban',
      'Kuala Sungai Baru',
      'Pulau Sebang',
    ],
    'Negeri Sembilan': [
      'Seremban',
      'Port Dickson',
      'Nilai',
      'Bahau',
      'Tampin',
      'Kuala Pilah',
    ],
    Pahang: [
      'Kuantan',
      'Temerloh',
      'Bentong',
      'Mentakab',
      'Raub',
      'Jerantut',
      'Pekan',
      'Kuala Lipis',
      'Bandar Jengka',
      'Bukit Tinggi',
    ],
    Perak: [
      'Ipoh',
      'Taiping',
      'Sitiawan',
      'Simpang Empat',
      'Teluk Intan',
      'Batu Gajah',
      'Lumut',
      'Kampung Koh',
      'Kuala Kangsar',
      'Sungai Siput Utara',
      'Tapah',
      'Bidor',
      'Parit Buntar',
      'Ayer Tawar',
      'Bagan Serai',
      'Tanjung Malim',
      'Lawan Kuda Baharu',
      'Pantai Remis',
      'Kampar',
    ],
    Perlis: ['Kangar', 'Kuala Perlis'],
    'Pulau Pinang': [
      'Bukit Mertajam',
      'Georgetown',
      'Sungai Ara',
      'Gelugor',
      'Ayer Itam',
      'Butterworth',
      'Val d’Or',
      'Perai',
      'Nibong Tebal',
      'Permatang Kucing',
      'Tanjung Tokong',
      'Kepala Batas',
      'Tanjung Bungah',
      'Juru',
    ],
    Sabah: [
      'Kota Kinabalu',
      'Sandakan',
      'Tawau',
      'Lahad Datu',
      'Keningau',
      'Putatan',
      'Donggongon',
      'Semporna',
      'Kudat',
      'Kunak',
      'Papar',
      'Ranau',
      'Beaufort',
      'Kinarut',
      'Kota Belud',
    ],
    Sarawak: [
      'Kuching',
      'Miri',
      'Sibu',
      'Bintulu',
      'Limbang',
      'Sarikei',
      'Sri Aman',
      'Kapit',
      'Batu Delapan Bazaar',
      'Kota Samarahan',
    ],
    Selangor: [
      'Subang Jaya',
      'Klang',
      'Ampang Jaya',
      'Shah Alam',
      'Petaling Jaya',
      'Cheras',
      'Kajang',
      'Selayang Baru',
      'Rawang',
      'Taman Greenwood',
      'Semenyih',
      'Banting',
      'Balakong',
      'Gombak Setia',
      'Kuala Selangor',
      'Serendah',
      'Bukit Beruntung',
      'Pengkalan Kundang',
      'Jenjarom',
      'Sungai Besar',
      'Batu Arang',
      'Tanjung Sepat',
      'Kuang',
      'Kuala Kubu Baharu',
      'Batang Berjuntai',
      'Bandar Baru Salak Tinggi',
      'Sekinchan',
      'Sabak',
      'Tanjung Karang',
      'Beranang',
      'Sungai Pelek',
    ],
    Terengganu: [
      'Kuala Terengganu',
      'Chukai',
      'Dungun',
      'Kerteh',
      'Kuala Berang',
      'Marang',
      'Paka',
      'Jerteh',
    ],
    'Wilayah Persekutuan': ['Kuala Lumpur', 'Labuan', 'Putrajaya'],
    //singapore
    'Central Region': [
      'Downtown Core',
      'Bishan',
      'Bukit Merah',
      'Bukit Timah',
      'Geylang',
      'Kallang',
      'Marina East',
      'Marina South',
      'Marine Parade',
      'Museum',
      'Newton',
      'Novena',
      'Orchard',
      'Outram',
      'Queenstown',
      'River Valley',
      'Rochor',
      'Singapore River',
      'Straits View',
      'Tanglin',
      'Toa Payoh',
    ],
    'North Region': ['Admiralty', 'Mandai', 'Sembawang', 'Woodlands', 'Yishun'],
    'Northeast Region': [
      'Ang Mo Kio',
      'Hougang',
      'Punggol',
      'Seletar',
      'Sengkang',
      'Serangoon',
    ],
    'East Region': ['Bedok', 'Changi', 'Pasir Ris', 'Tampines'],
    'West Region': [
      'Boon Lay',
      'Bukit Batok',
      'Bukit Panjang',
      'Choa Chu Kang',
      'Clementi',
      'Jurong East',
      'Jurong West',
      'Pioneer',
      'Tengah',
      'Tuas',
      'Western Islands',
    ],
    //morocco
    'Tanger-Tetouan-Al Hoceima': [
      'Tanger-Assilah',
      'Fahs-Anjra',
      "M'diq-Fnideq",
      'Tétouan',
      'Larache',
      'Al Hoceïma',
    ],
    Oriental: [
      'Oujda-Angad',
      'Nador',
      'Berkane',
      'Taourirt',
      'Jerada',
      'Figuig',
    ],
    'Fès-Meknès': [
      'Fès',
      'Meknès',
      'El Hajeb',
      'Ifrane',
      'Sefrou',
      'Boulemane',
      'Taounate',
    ],
    'Rabat-Salé-Kénitra': [
      'Rabat',
      'Salé',
      'Skhirate-Témara',
      'Kénitra',
      'Sidi Kacem',
      'Sidi Slimane',
    ],
    'Béni Mellal-Khénifra': [
      'Béni Mellal-Khénifra',
      'Azilal',
      'Fquih Ben Salah',
      'Khouribga',
      'Béni Mellal',
    ],
    'Casablanca-Settat': [
      'Casablanca',
      'Mohammadia',
      'Benslimane',
      'Settat',
      'El Jadida',
      'Nouaceur',
    ],
    'Marrakech-Safi': [
      'Marrakech',
      'Essaouira',
      'Al Haouz',
      'Chichaoua',
      'El Kelaa des Sraghna',
      'Safi',
      'Youssoufia',
    ],
    'Drâa-Tafilalet': [
      'Errachidia',
      'Ouarzazate',
      'Midelt',
      'Tinghir',
      'Zagora',
      'Tata',
    ],
    'Souss-Massa': [
      'Agadir-Ida Ou Tanane',
      'Inezgane-Ait Melloul',
      'Chtouka-Ait Baha',
      'Taroudant',
      'Tiznit',
    ],
    'Guelmim-Oued Noun': ['Guelmim', 'Assa-Zag', 'Tan-Tan'],
    'Laâyoune-Sakia El Hamra': ['Laâyoune', 'Boujdour', 'Tarfaya'],
    'Dakhla-Oued Ed-Dahab': ['Aousserd', 'Oued Ed-Dahab'],
    //egypt
    Alexandria: ['Alexandria'],
    Aswan: ['Aswan'],
    Asyut: ['Asyut'],
    Beheira: ['Damanhur', 'Rashid', 'Edku', 'Kom Hamada'],
    'Beni Suef': ['Beni Suef'],
    Cairo: ['Cairo'],
    Dakahlia: ['Mansoura'],
    Damietta: ['Damietta'],
    Faiyum: ['Faiyum'],
    Gharbia: ['Tanta'],
    Giza: ['Giza', '6th of October City'],
    Ismailia: ['Ismailia'],
    'Kafr El Sheikh': ['Kafr El Sheikh'],
    Luxor: ['Luxor'],
    Matrouh: ['Marsa Matrouh'],
    Minya: ['Minya'],
    Monufia: ['Shibin El Kom'],
    'New Valley': ['Kharga', 'Dakhla', 'Farafra'],
    'North Sinai': ['Arish'],
    'Port Said': ['Port Said'],
    Qalyubia: ['Banha'],
    Qena: ['Qena'],
    'Red Sea': ['Hurghada'],
    Sharqia: ['Zagazig'],
    Sohag: ['Sohag'],
    'South Sinai': ['Sharm El Sheikh', 'Dahab', 'Nuweiba', 'Saint Catherine'],
    Suez: ['Suez'],
    //kenya
    Baringo: [
      'Baringo Central',
      'Baringo North',
      'Baringo South',
      'Eldama Ravine',
      'Mochongoi',
      'Mogotio',
      'Tiaty',
    ],
    Bomet: [
      'Bomet Central',
      'Bomet East',
      'Bomet West',
      'Chepalungu',
      'Konoin',
      'Sotik',
    ],
    Bungoma: [
      'Bumula',
      'Kanduyi',
      'Kimilili',
      'Mount Elgon',
      'Sirisia',
      'Tongaren',
      'Webuye East',
      'Webuye West',
    ],
    Busia: ['Budalangi', 'Bunyala', 'Butula', 'Funyula', 'Matayos', 'Namwala'],
    'Elgeyo-Marakwet': [
      'Cherangany',
      'Kapsowar',
      'Keiyo North',
      'Keiyo South',
      'Marakwet East',
      'Marakwet West',
    ],
    Embu: ['Manyatta', 'Mbeere North', 'Mbeere South', 'Runyenjes'],
    Garissa: [
      'Balambala',
      'Dadaab',
      'Fafi',
      'Garissa Township',
      'Hulugho',
      'Ijara',
      'Lagdera',
    ],
    'Homa Bay': [
      'Homa Bay Town',
      'Kabondo Kasipul',
      'Karachuonyo',
      'Kasipul',
      'Mbita',
      'Ndhiwa',
      'Rangwe',
    ],
    Isiolo: ['Central', 'Garbatulla', 'Isiolo North', 'Isiolo South', 'Merti'],
    Kajiado: [
      'Isinya',
      'Kajiado Central',
      'Kajiado East',
      'Kajiado North',
      'Loitokitok',
      'Magadi',
      'Namanga',
    ],
    Kakamega: [
      'Butere',
      'Kakamega Central',
      'Kakamega East',
      'Kakamega North',
      'Kakamega South',
      'Khwisero',
      'Lugari',
      'Lurambi',
      'Matete',
      'Matungu',
      'Mumias East',
      'Mumias West',
      'Navakholo',
    ],
    Kericho: [
      'Ainamoi',
      'Belgut',
      'Bureti',
      'Kipkelion East',
      'Kipkelion West',
      'Soin/Sigowet',
    ],
    Kiambu: [
      'Gatundu North',
      'Gatundu South',
      'Githunguri',
      'Juja',
      'Kabete',
      'Kiambaa',
      'Kikuyu',
      'Limuru',
      'Ruiru',
      'Thika Town',
    ],
    Kilifi: [
      'Ganze',
      'Kaloleni',
      'Kilifi North',
      'Kilifi South',
      'Magarini',
      'Malindi',
      'Rabai',
    ],
    Kirinyaga: [
      'Gichugu',
      'Kirinyaga Central',
      'Kirinyaga East',
      'Kirinyaga West',
      'Mwea East',
      'Mwea West',
    ],
    Kisii: [
      'Bobasi',
      'Bomachoge Borabu',
      'Bomachoge Chache',
      'Kitutu Chache North',
      'Kitutu Chache South',
      'South Mugirango',
      'West Mugirango',
    ],
    Kisumu: [
      'Kisumu Central',
      'Kisumu East',
      'Kisumu West',
      'Muhoroni',
      'Nyakach',
      'Nyando',
      'Seme',
    ],
    Kitui: [
      'Ikutha',
      'Kisasi',
      'Kitui Central',
      'Kitui East',
      'Kitui Rural',
      'Kitui South',
      'Kitui West',
      'Lower Yatta',
      'Matiangi',
      'Mumoni',
    ],
    Kwale: ['Kinango', 'Lunga Lunga', 'Matuga', 'Msambweni'],
    Laikipia: ['Laikipia East', 'Laikipia North', 'Laikipia West', 'Nanyuki'],
    Lamu: ['Lamu East', 'Lamu West'],
    Machakos: [
      'Athi River',
      'Kangundo',
      'Kathiani',
      'Masinga',
      'Matungulu',
      'Mavoko',
      'Mwala',
      'Yatta',
    ],
    Makueni: [
      'Kaiti',
      'Kibwezi East',
      'Kibwezi West',
      'Kilome',
      'Makueni',
      'Mbooni',
    ],
    Mandera: [
      'Banisa',
      'Lafey',
      'Mandera East',
      'Mandera North',
      'Mandera South',
      'Mandera West',
      'Rhamu',
    ],
    Marsabit: ['Laisamis', 'Moyale', 'North Horr', 'Saku', 'Sololo'],
    Meru: [
      'Buuri',
      'Igembe Central',
      'Igembe North',
      'Igembe South',
      'Imenti Central',
      'Imenti North',
      'Imenti South',
      'Meru Central',
      'Meru South',
      'Meru West',
      'Tigania East',
      'Tigania West',
    ],
    Migori: [
      'Awendo',
      'Kuria East',
      'Kuria West',
      'Mabera',
      'Rongo',
      'Suna East',
      'Suna West',
      'Uriri',
    ],
    Mombasa: ['Changamwe', 'Jomvu', 'Kisauni', 'Likoni', 'Mvita', 'Nyali'],
    "Murang'a": [
      'Gatanga',
      'Kahuro',
      'Kandara',
      'Kangema',
      'Kigumo',
      'Kiharu',
      'Mathioya',
      "Murang'a East",
      "Murang'a South",
      'Muruaki',
      'Muthithi',
    ],
    Nairobi: [
      'Dagoretti North',
      'Dagoretti South',
      'Embakasi Central',
      'Embakasi East',
      'Embakasi North',
      'Embakasi South',
      'Embakasi West',
      'Kamukunji',
      'Kasarani',
      'Kibra',
      "Lang'ata",
      'Makadara',
      'Mathare',
      'Nairobi West',
      'Roysambu',
      'Ruaraka',
      'Starehe',
      'Westlands',
    ],
    Nakuru: [
      'Bahati',
      'Gilgil',
      'Kuresoi North',
      'Kuresoi South',
      'Molo',
      'Naivasha',
      'Nakuru East',
      'Nakuru West',
      'Njoro',
      'Rongai',
      'Subukia',
    ],
    Nandi: [
      'Aldai',
      'Chesumei',
      'Emgwen',
      'Mosop',
      'Nandi East',
      'Nandi Hills',
      'Tindiret',
    ],
    Narok: [
      'Emurua Dikirr',
      'Kilgoris',
      'Narok East',
      'Narok North',
      'Narok South',
    ],
    Nyamira: [
      'Borabu',
      'Manga',
      'Masaba North',
      'Masaba South',
      'Nyamira North',
      'Nyamira South',
    ],
    Nyandarua: ['Kinangop', 'Kipipiri', 'Ndaragwa', 'Ol Joro Orok'],
    Nyeri: [
      'Kieni East',
      'Kieni West',
      'Mathira East',
      'Mathira West',
      'Mukurweini',
      'Nyeri Central',
      'Nyeri South',
      'Tetu',
    ],
    Samburu: ['Samburu Central', 'Samburu East', 'Samburu North'],
    Siaya: ['Alego Usonga', 'Gem', 'Rarieda', 'Ugenya', 'Ugunja'],
    'Taita-Taveta': ['Mwatate', 'Taveta', 'Voi', 'Wundanyi'],
    'Tana River': ['Bura', 'Galole', 'Garsen'],
    'Tharaka-Nithi': ['Chuka', "Igambang'ombe", 'Maara', 'Tharaka'],
    'Trans Nzoia': ['Cherangany', 'Endebess', 'Kiminini', 'Kwanza', 'Saboti'],
    Turkana: [
      'Loima',
      'Turkana Central',
      'Turkana East',
      'Turkana North',
      'Turkana South',
      'Turkana West',
    ],
    'Uasin Gishu': ['Ainabkoi', 'Kapseret', 'Kesses', 'Moiben', 'Soy', 'Turbo'],
    Vihiga: ['Emuhaya', 'Hamisi', 'Luanda', 'Sabatia', 'Vihiga'],
    Wajir: [
      'Eldas',
      'Tarbaj',
      'Wajir East',
      'Wajir North',
      'Wajir South',
      'Wajir West',
    ],
    'West Pokot': ['Kacheliba', 'Pokot Central', 'Pokot North', 'Pokot South'],
  };
}
